**Decision Tree Regression** 

In [12]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [13]:
#import dataset
data=pd.read_csv("/content/Position_Salaries.csv")
x=data.iloc[:,1:-1].values
y=data.iloc[:,-1].values

In [14]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [15]:
y

array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

Training Deceinon tree model

In [16]:
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(x,y)

DecisionTreeRegressor(random_state=0)

In [17]:
y_pred=regressor.predict([[6.5]])
y_pred

array([150000.])

Vsualization result




In [19]:
x_grid=np.arange(min(x),max(x),0.1)
x_grid=x_grid.reshape((len(x_grid),1))
plt.scatter(x,y,color="blue")
plt.plot(x_grid,regressor.predict(x_grid),color="red")
plt.title("DEcission tree regressor")
plt.xlabel("position")
plt.ylabel("Salary")
plt.show()

In [20]:
plt.scatter(x,y,color="blue")
plt.plot(x,regressor.predict(x),color="red")
plt.title("DEcission tree regressor")
plt.xlabel("position")
plt.ylabel("Salary")
plt.show()

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)